name: Workspace Consistency Checks

on:
  workflow_call:

jobs:
  install:
    runs-on: ubuntu-latest-4-cores
    strategy:
      matrix:
        deno-version: [2.2.x]
        module: [
          core,
          jetstream,
          kv,
          obj,
          services,
          transport-deno,
          transport-node,
        ]

    steps:
      - name: Git Checkout Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Lint Deno Modules
        run: |
          deno fmt --check ${{ matrix.module }}/
          deno lint ${{ matrix.module }}/

      - name: Check Versions
        run: |
          deno run -A bin/check-bundle-version.ts --module ${{ matrix.module }}
          deno task check-dependencies
