name: Workspace Deno Tests

on:
  workflow_call:

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [2.4.x]
        module: [core, jetstream, kv, obj, services, transport-deno]

    steps:
      - name: Git Checkout Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Install nats-server
        uses: aricart/install-binary@v1.0.0
        with:
          repo: nats-io/nats-server
          name: nats-server
          cache: true

      - name: Test
        env:
          NGS_CI_USER: ${{ secrets.NGS_CI_USER }}
          TMPDIR: ${{ runner.temp }}
          CI: true
        run: |
          deno task test-${{ matrix.module }}
          deno task coverage

      - name: Upload coverage
        uses: coverallsapp/github-action@v2
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ${{ matrix.module }}
          file: ./coverage/out.lcov

