name: Workspace Node Tests

on:
  workflow_call:

jobs:
  node-tests-workspace:
    runs-on: ubuntu-latests
    strategy:
      matrix:
        deno-version: [2.2.x]
        node-version: [23.x]

    steps:
      - name: Git Checkout Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Install nats-server
        uses: aricart/install-binary@v1.0.0
        with:
          repo: nats-io/nats-server
          name: nats-server
          cache: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test Node with Workspace Dependencies
        env:
          NGS_CI_USER: ${{ secrets.NGS_CI_USER }}
          TMPDIR: ${{ runner.temp }}
          CI: true
        run: |
          npm install --workspaces
          npm run prepack --workspaces
          npm run coverage --workspace transport-node

      - name: Upload coverage
        uses: coverallsapp/github-action@v2
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: transport-node
          file: ./transport-node/out.lcov

