name: NPM/JSR release

on:
  release:
    types: [created]

jobs:
  test:
    strategy:
      matrix:
        node-version: [23.x]
        deno-version: [2.2.x]

    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout nats.js
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Set tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Dry run
        run: |
          deno publish --allow-dirty --dry-run
          npm install --workspaces
          npm publish --provenance --access public --tag=latest --workspaces --dry-run
          npm run clean --workspaces
      - name: Publish JSR
        run: deno publish --allow-dirty

      - name: Publish NPM core
        run: npm publish --provenance --access public --tag=latest --workspaces core
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish NPM jetstream
        run: npm publish --provenance --access public --tag=latest --workspaces jetstream
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish NPM kv
        run: npm publish --provenance --access public --tag=latest --workspaces kv
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish NPM obj
        run: npm publish --provenance --access public --tag=latest --workspaces obj
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish NPM services
        run: npm publish --provenance --access public --tag=latest --workspaces services
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish NPM transport-node
        run: npm publish --provenance --access public --tag=latest --workspaces transport-node
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}