name: NPM/JSR release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        node-version: [24.x]
        deno-version: [2.4.x]

    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout nats.js
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Set tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Dry run
        run: |
          deno publish --allow-dirty --dry-run
          npm install --workspaces
          npm publish --provenance --access public --tag=latest --workspaces --dry-run
          npm run clean --workspaces

      - name: Publish JSR
        run: deno publish --allow-dirty

      - name: Build Bundles
        run:  npm run build --workspaces

      - name: Publish NPM core
        run: |
          cd core
          npm publish --provenance --access public --tag=latest
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish NPM jetstream
        run: |
          cd jetstream
          npm publish --provenance --access public --tag=latest
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish NPM kv
        run: |
          cd kv
          npm publish --provenance --access public --tag=latest
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish NPM obj
        run: |
          cd obj
          npm publish --provenance --access public --tag=latest
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish NPM services
        run: | 
          cd services
          npm publish --provenance --access public --tag=latest
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish NPM transport-node
        run: |
          cd transport-node
          npm publish --provenance --access public --tag=latest
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}