name: obj release

on:
  push:
    paths:
      - "obj/**"
      - ".github/workflows/obj.yml"
    tags: ["obj/*"]
    branches:
      - "*"
jobs:
  test:
    name: test obj with released dependencies
    runs-on: ubuntu-latest-4-cores
    strategy:
      matrix:
        deno-version: [2.0.x]

    steps:
      - name: Git Checkout Core
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install nats-server
        uses: aricart/install-binary@v1.0.0
        with:
          repo: nats-io/nats-server
          name: nats-server
          cache: true

      - name: Disable NPM workspace
        run: |
          deno task disable-npm-workspace

      - name: Test Deno Module
        working-directory: obj
        env:
          TMPDIR: ${{ runner.temp }}
          CI: true
          NGS_CI_USER: ${{ secrets.NGS_CI_USER }}
        run: |
          deno task test

      - name: Build NPM core bundle
        working-directory: obj
        env:
          CI: true
        run: |
          npm install
          npm run prepack
          npm link

      - name: Test Node Transport with local obj
        working-directory: transport-node
        env:
          CI: true
        run: |
          npm install
          npm run prepack
          npm link @nats-io/obj
          npm test
